# -*- coding: utf-8 -*-
"""Bridge_Teclado-PC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11HZfGrL8ZxWgoYkJVO3i4NCmODBEsh6_
"""

from abc import ABC, abstractmethod

class Computador(ABC):
  @abstractmethod
  def escreverCaractere(self, caractere: str):
    pass
  @abstractmethod
  def copiarTexto(self, txt: str):
    pass
  @abstractmethod
  def colarTexto(self, txt: str):
    pass
  @abstractmethod
  def alterarVolume(self, volume: int):
    pass
  @abstractmethod
  def mudo(self):
    pass
  @abstractmethod
  def obterVolume(self,):
    pass
  @abstractmethod
  def alterarReproducao(self, reproducao: str):
    pass

class NotebookWindows(Computador):
  def __init__(self):
    self._areaTransferencia = ""
    self._midia = ""
    self._volume = 0
    self.listaMidias = []

  def escreverCaractere(self, caractere: str):
    print(caractere, end="")
  
  def copiarTexto(self, txt: str):
    self._areaTransferencia = txt
  
  def colarTexto(self, txt: str):
    return self._areaTransferencia 
  
  def alterarVolume(self, volume: int):
    if (0 <= volume <= 100):
      self._volume = volume
    return self._volume
  
  def mudo(self):
    self._volume = 0
  
  def obterVolume(self):
    return self._volume
  
  def alterarReproducao(self, reproducao: str):
    idxAtual = self.listaMidias.index(self._midia)
    if (reproducao == '>'):
      self._midia = self.listaMidias[idxAtual+1]
      return self._midia
    elif (reproducao == '<'):
      self._midia = self.listaMidias[idxAtual-1]
      return self._midia
  
  def definirMidias(self, midias):
    self.listaMidias = midias
    self._midia = midias[0]

class Macbook(Computador):
  def __init__(self):
    self._areaTransferencia = None
    self._midia = None
    self._volume = 0
    self.proximaMidia = None
    self.ultimaMidia = None

  def escreverCaractere(self, caractere: str):
    print(caractere, end="")
  
  def copiarTexto(self, txt: str):
    self._areaTransferencia = txt
  
  def colarTexto(self, txt: str):
    if (self._areaTransferencia is None):
      self._areaTransferencia = ""
    print(self._areaTransferencia )
  
  def alterarVolume(self, volume: int):
    if (0 <= volume <= 50):
      self._volume = volume
    return self._volume

  def mudo(self):
    self._volume = 0
  
  def obterVolume(self):
    return self._volume
 
  def alterarReproducao(self, reproducao: str):
    if (reproducao == '>'):
      self._midia, self.proximaMidia, self.ultimaMidia = self.proximaMidia, self.ultimaMidia, self._midia
      return self._midia
    elif (reproducao == '<'):
      self._midia, self.proximaMidia, self.ultimaMidia = self.ultimaMidia, self._midia, self.proximaMidia
      return self._midia

  def definirMidias(self, proxima: str, atual: str, anterior: str):
    self.proximaMidia = proxima
    self.ultimaMidia = anterior
    self._midia = atual

class Teclado:
  def __init__(self, computador: Computador):
    self.computador = computador
  
  def digitar(self, caractere: str):
    return self.computador.escreverCaractere(caractere)
  
  def comando(self, caractere, valor=""):
    if (caractere == "c"):
      return self.computador.copiarTexto(valor)
    if (caractere == "v"):
      return self.computador.colarTexto()

class TecladoControleMidia(Teclado):
  def aumentarVolume(self):
    novoVolume = self.computador.obterVolume() + 1
    return self.computador.alterarVolume(novoVolume)

  def diminuirVolume(self):
    novoVolume = self.computador.obterVolume() - 1
    return self.computador.alterarVolume(novoVolume)

  def mutar(self):
    self.computador.mudo()

  def proximaMidia(self):
    return self.computador.alterarReproducao('>')
  
  def midiaAnterior(self):
    return self.computador.alterarReproducao('<')

if __name__ == "__main__":
  notebook = NotebookWindows()
  notebook.definirMidias(["musica1", "musica2", "musica3", "musica4"])

  tecladoSoft = TecladoControleMidia(notebook)
  print("Diminuindo volume")
  print(f"{tecladoSoft.diminuirVolume()}")
  print(f"{tecladoSoft.diminuirVolume()}")
  print(f"{tecladoSoft.aumentarVolume()}")

  print("\nProxima Midia")
  print(f"{tecladoSoft.proximaMidia()}")
  print(f"{tecladoSoft.proximaMidia()}")